wget https://upload.wikimedia.org/wikipedia/commons/0/0c/Draughts_mdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/1/15/Chess_qlt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/1/17/Yin_yang.svg
wget https://upload.wikimedia.org/wikipedia/commons/4/42/Chess_klt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/4/45/Chess_plt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/4/47/Chess_qdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/6/65/White_Stars_1.svg
wget https://upload.wikimedia.org/wikipedia/commons/7/70/Chess_nlt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/7/72/Chess_rlt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/9/90/Draughts_mlt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/9/98/Chess_bdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/9/9a/Draughts_kdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/a/a6/Draughts_klt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/b/b1/Chess_blt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/c/c7/Chess_pdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/c/c8/Black_Star.svg
wget https://upload.wikimedia.org/wikipedia/commons/e/ef/Chess_ndt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/f/f0/Chess_kdt45.svg
wget https://upload.wikimedia.org/wikipedia/commons/f/ff/Chess_rdt45.svg
